
CREATE TABLE "PERSON" (
	"ID"	char(20)		NOT NULL,
	"NAME"	char(30)		NULL,
	"GENDER"	number(13)		NULL,
	"YEAR"	number(3)		NULL,
	"pw"	char(20)		NULL
);
CREATE SEQUENCE board_seq;

drop SEQUENCE board_seq;

SELECT * FROM ACCOUNT;
select * from ACC_W_D;

SELECT ACC_NAME FROM ACCOUNT WHERE ACC_CODE=0;

insert into ACCOUNT values(3,'');
insert into OWNACCOUNT values(123,50000,1,'wnddnr');
insert into OWNACCOUNT values(200,1000,0,'wnddnr');
select * from  OWNACCOUNT
			   OWNACCOUNT WHERE;
CREATE TABLE "ACCOUNT" (
	"ACC_CODE"	number(13)		NOT NULL,
	"ACC_NAME"	char(10)		NULL
);

CREATE TABLE "OWNACCOUNT" (
	"ACC_NUM"	number(13)		NOT NULL,
	"BALANCE"	number(10)		NULL,
	"ACC_CODE"	number(10)		NOT NULL,
	"ID"	char(12)		NOT NULL
);

CREATE TABLE "ACC_W_D" (
	"Key"	number		NOT NULL,
	"MONEY"	number(7)		NULL,
	"TRA_TIME"	timestamp		NULL,
	"GET_ACC"	number(13)		NOT NULL,
	"GIVE_ACC"	number(13)		NOT NULL
);

ALTER TABLE "PERSON" ADD CONSTRAINT "PK_PERSON" PRIMARY KEY (
	"ID"
);

ALTER TABLE "ACCOUNT" ADD CONSTRAINT "PK_ACCOUNT" PRIMARY KEY (
	"ACC_CODE"
);

ALTER TABLE "OWNACCOUNT" ADD CONSTRAINT "PK_OWNACCOUNT" PRIMARY KEY (
	"ACC_NUM"
);

ALTER TABLE "ACC_W_D" ADD CONSTRAINT "PK_ACC_W_D" PRIMARY KEY (
	"Key"
);
